"""Site assistant: write the chatbot's reference text and add the widget to every page.

Runs from build_site.py after llms-full.txt is written.
- api/_knowledge.js: llms-full.txt + the YouTube video list, imported by api/chat.js.
- <script src="/chat-widget.js" defer> before </body> on every HTML page (idempotent).
"""

import glob
import json
import os

import videos
from site_shell import ROOT, SITE

TAG = '<script src="/chat-widget.js" defer></script>'
CHANNEL = "https://www.youtube.com/@lida4ever"


def knowledge():
    text = open(os.path.join(ROOT, "llms-full.txt"), encoding="utf-8").read().strip()
    lines = [f"## TapeBackup YouTube channel: {CHANNEL}"]
    for path, v in videos.VIDEOS.items():
        lines.append(f"- {v['title']}: https://youtu.be/{v['id']} (shown on {SITE}/{path}). {v['desc']}")
    text += "\n\n" + "\n".join(lines) + "\n"
    out = os.path.join(ROOT, "api", "_knowledge.js")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    body = "// Generated by scripts/chatbot.py from llms-full.txt and scripts/videos.py. Do not edit.\nexport default " + json.dumps(text, ensure_ascii=False) + ";\n"
    if not os.path.exists(out) or open(out, encoding="utf-8").read() != body:
        open(out, "w", encoding="utf-8").write(body)
    return len(text)


def add_widget():
    n = 0
    for f in glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True):
        if os.sep + ".build" + os.sep in f or os.sep + "node_modules" + os.sep in f:
            continue
        s = open(f, encoding="utf-8").read()
        if TAG in s or "</body>" not in s:
            continue
        open(f, "w", encoding="utf-8").write(s.replace("</body>", TAG + "\n</body>", 1))
        n += 1
    return n


def build():
    return knowledge(), add_widget()
